// Mocks generated by Mockito 5.4.2 from annotations
// in mp5/test/WeatherAPI_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mp5/services/APIservices.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WeatherAPIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherAPIService extends _i1.Mock implements _i2.WeatherAPIService {
  MockWeatherAPIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: '',
      ) as String);

  @override
  _i3.Future<Map<String, dynamic>> fetchWeatherByCityName(String? cityName) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchWeatherByCityName,
          [cityName],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
